// Generated by scripts/generate.mjs from spec/openapi-admin.yaml. Do not edit;
// change the document and run `npm run generate`.

/** The draft of spec/protocol.md this package was generated against. */
export const PROTOCOL_DRAFT = "0.33";

/** The info.version of spec/openapi-admin.yaml this package was generated from. */
export const OPENAPI_VERSION = "0.13.0";
