// Package panel is the optional web UI of the reference hub: a handful of
// static files, embedded in the binary, that a browser turns into an operator
// console. It is a thin client over the Admin API and nothing more. The Go
// side of it is only a file server with the response headers a page that
// holds a bearer token deserves; every decision about servers, manifests, and
// actions is made by the JavaScript in static/ through /api/v1, with the
// same bearer tokens and the same scopes as curl.
//
// The one thing the panel serves that is not embedded is map tilesets: the
// basemap the live map view draws players on is game-specific imagery of
// tens of megabytes per world, generated by the operator (see
// spikes/chernarus-satellite for the DayZ pipeline) and installed in a
// directory the hub is pointed at. They are served under /maps/ with the
// same posture as the page itself.
//
// The hub does not import this package. It takes the handler through
// hub.Config.Panel, so the hub stays free of UI and an embedder may mount a
// different panel or none.
package panel

import (
	"embed"
	"encoding/json"
	"errors"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

//go:embed static
var static embed.FS

// Config is what a panel may be given beyond its embedded files.
type Config struct {
	// MapsDir is a directory of map tilesets, one subdirectory per world id
	// (the value a plugin reports as `world` in its core.server.start event:
	// `chernarusplus`, `enoch`), each holding a manifest.json and its tiles.
	// Empty serves no maps, and the map view lists players without a basemap.
	MapsDir string
}

// Handler serves the panel with no map tilesets. Handler is NewHandler with
// an empty Config.
func Handler() http.Handler {
	return NewHandler(Config{})
}

// NewHandler serves the panel rooted at "/": index.html at the root, the
// assets beside it, and, when a maps directory is configured, the tilesets
// under /maps/. Mount it under a prefix with http.StripPrefix.
//
// Every response carries a Content-Security-Policy that confines the page to
// its own origin with no inline script or style, which is what makes the
// admin token the page holds unreachable from anything but the panel's own
// code: a manifest is plugin-supplied text, and the panel renders labels and
// codes from it, so the policy is the backstop should a rendering path ever
// treat one as markup. The page is also refused to framers, sends no
// referrer, and asks browsers to revalidate rather than cache, so an upgraded
// hub is never driven by a stale panel.
func NewHandler(cfg Config) http.Handler {
	root, err := fs.Sub(static, "static")
	if err != nil {
		// The directory is embedded at compile time; a missing subtree is a
		// build defect, not a runtime condition.
		panic("panel: embedded static directory missing: " + err.Error())
	}
	files := http.FileServerFS(root)
	maps := mapsFrom(cfg.MapsDir)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		header := w.Header()
		header.Set("Content-Security-Policy", contentSecurityPolicy)
		header.Set("X-Content-Type-Options", "nosniff")
		header.Set("X-Frame-Options", "DENY")
		header.Set("Referrer-Policy", "no-referrer")
		header.Set("Cache-Control", "no-cache")
		if rest, isMap := strings.CutPrefix(r.URL.Path, "/maps/"); isMap {
			maps.serve(w, r, rest)
			return
		}
		// The panel is flat: its files live at the root and nowhere else.
		// Refusing every deeper path here, before FileServer sees it, is
		// what keeps FileServer's own behaviours off the wire: it would
		// list a directory, and it redirects any path ending in /index.html
		// to its directory before checking that either exists. A missing
		// file is refused in the hub's error shape rather than FileServer's
		// plain text, so every failure from the hub's port parses the same
		// way whichever surface answered it.
		if strings.Count(r.URL.Path, "/") > 1 || !shipped(root, r.URL.Path) {
			notFound(w, r)
			return
		}
		files.ServeHTTP(w, r)
	})
}

// shipped reports whether a request path names a file in the embedded tree;
// "/" is the index and always present.
func shipped(root fs.FS, path string) bool {
	if path == "/" || path == "/index.html" {
		return true
	}
	info, err := fs.Stat(root, strings.TrimPrefix(path, "/"))
	return err == nil && !info.IsDir()
}

// worldID is the shape of a world directory name. It is a plugin-reported
// identifier that becomes a path segment, so it is kept to characters that
// cannot mean anything to a path or a URL.
var worldID = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)

// mapsDir is the tileset surface over one directory; a nil *mapsDir serves
// nothing.
type mapsDir struct {
	dir string
}

func mapsFrom(dir string) *mapsDir {
	if dir == "" {
		return nil
	}
	return &mapsDir{dir: dir}
}

// serve answers the tileset surface: "/maps/" is the index of installed
// worlds, "/maps/{world}/manifest.json" a world's dataset contract, and
// "/maps/{world}/tiles/..." its tiles. Nothing else under a world directory
// is reachable: a build leaves large intermediates (a lossless master
// raster, decoded sources) beside the tiles, and an unauthenticated surface
// should not stream those to whoever guesses a name. Directories are never
// listed. Tiles are immutable per dataset and may be cached; the index and
// the manifest are revalidated like the page.
//
// Links are followed at two places only, because an operator builds a
// dataset elsewhere and links it in: the world directory itself, and its
// tiles directory. Each is opened as an os.Root, and the file is opened
// inside that root, so the boundary is enforced by the open itself rather
// than by comparing paths beforehand: nothing beneath the tiles directory
// can reach outside it, a directory swapped for a link between a check and
// the open cannot widen anything, and no case folding or path spelling
// takes part. The manifest and a tile may not themselves be links.
//
// What ServeContent refuses on its own (an unsatisfiable Range, a failed
// precondition) is answered in its plain form; the refusals this surface
// decides, a missing or unreachable file, keep the protocol's shape.
func (m *mapsDir) serve(w http.ResponseWriter, r *http.Request, rest string) {
	if m == nil {
		notFound(w, r)
		return
	}
	if rest == "" {
		worlds, err := m.installedWorlds()
		if err != nil {
			serverError(w, "the maps directory could not be read")
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{"worlds": worlds})
		return
	}
	world, file, hasFile := strings.Cut(rest, "/")
	if !hasFile || !worldID.MatchString(world) {
		notFound(w, r)
		return
	}
	// The raw segment is validated, not a cleaned one: a climb inside it
	// ("tiles/../master.png") must be refused here rather than resolved.
	if !fs.ValidPath(file) || (file != "manifest.json" && !strings.HasPrefix(file, "tiles/")) {
		notFound(w, r)
		return
	}
	rootPath := filepath.Join(m.dir, world)
	name := file
	if file != "manifest.json" {
		rootPath = filepath.Join(rootPath, "tiles")
		name = strings.TrimPrefix(file, "tiles/")
	}
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		notFound(w, r)
		return
	}
	defer root.Close()
	// The file is opened and served here rather than through ServeFileFS,
	// which would redirect a path ending in index.html and answer an open
	// failure in its own plain text.
	handle, err := root.Open(name)
	if err != nil {
		notFound(w, r)
		return
	}
	defer handle.Close()
	info, err := handle.Stat()
	if err != nil || info.IsDir() {
		notFound(w, r)
		return
	}
	// The name itself may not be a link, whatever it points at: the root
	// keeps a link inside the world, and the world holds the build's
	// intermediates beside the manifest. The link check follows the open
	// rather than preceding it, and the opened file must be the one the
	// name denotes now, so a name swapped for a link in between refuses
	// rather than serves. A directory link beneath the tiles is followed
	// by the root only while it stays inside the tiles.
	denoted, err := root.Lstat(name)
	if err != nil || denoted.Mode()&fs.ModeSymlink != 0 || !os.SameFile(denoted, info) {
		notFound(w, r)
		return
	}
	if file != "manifest.json" {
		w.Header().Set("Cache-Control", "public, max-age=3600")
	}
	http.ServeContent(w, r, path.Base(file), info.ModTime(), handle)
}

// installedWorlds lists the world directories that hold a manifest.json, in
// name order. A directory the hub cannot read is an error; an entry that is
// not a world (a stray file, a name outside the world shape, a directory
// without a manifest) is simply not a world. Whether an entry is a directory
// is decided through any link it is (a symlink or a Windows junction to a
// dataset built elsewhere), and whether the manifest is one is decided
// without following a link, the same way each is served, so that a world
// that answers is a world that is listed and no other.
func (m *mapsDir) installedWorlds() ([]string, error) {
	entries, err := os.ReadDir(m.dir)
	if err != nil {
		return nil, err
	}
	worlds := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !worldID.MatchString(entry.Name()) {
			continue
		}
		dir, err := os.Stat(filepath.Join(m.dir, entry.Name()))
		if err != nil || !dir.IsDir() {
			// A dangling link is not a world either.
			continue
		}
		info, err := os.Lstat(filepath.Join(m.dir, entry.Name(), "manifest.json"))
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				continue
			}
			return nil, err
		}
		if !info.Mode().IsRegular() {
			continue
		}
		worlds = append(worlds, entry.Name())
	}
	sort.Strings(worlds)
	return worlds, nil
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

// notFound answers in the protocol's error shape (spec section 2.2). The
// panel is not part of either API realm, but a client that reads the hub's
// errors should be able to read this one too.
func notFound(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusNotFound, map[string]any{
		"error": map[string]string{"code": "not_found", "message": "the panel has no file at " + r.URL.Path},
	})
}

func serverError(w http.ResponseWriter, message string) {
	writeJSON(w, http.StatusInternalServerError, map[string]any{
		"error": map[string]string{"code": "internal", "message": message},
	})
}

// contentSecurityPolicy is the policy every panel response carries. Scripts,
// styles, and fetches may reach this origin only; images may additionally be
// inline data URLs for the favicon; nothing may be embedded, framed, or used
// as a form action, because the panel submits nothing as a form.
const contentSecurityPolicy = "default-src 'none'; " +
	"script-src 'self'; " +
	"style-src 'self'; " +
	"connect-src 'self'; " +
	"img-src 'self' data:; " +
	"font-src 'self'; " +
	"base-uri 'none'; " +
	"form-action 'none'; " +
	"frame-ancestors 'none'"
