// Generates src/schema.ts and src/version.ts from the repository's spec
// documents: the types from spec/openapi-admin.yaml, and the two version
// constants from the header of spec/protocol.md and the document's
// info.version. `--check` regenerates in memory and fails when a committed
// file differs, which is how CI keeps the package from drifting behind the
// document it is generated from.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { parse } from "yaml";

const root = new URL("../../../", import.meta.url);
const openapiURL = new URL("spec/openapi-admin.yaml", root);
const protocolURL = new URL("spec/protocol.md", root);
const schemaURL = new URL("../src/schema.ts", import.meta.url);
const versionURL = new URL("../src/version.ts", import.meta.url);

const banner =
  "// Generated by scripts/generate.mjs from spec/openapi-admin.yaml. Do not edit;\n" +
  "// change the document and run `npm run generate`.\n\n";

async function render() {
  const document = await readFile(openapiURL, "utf8");
  const ast = await openapiTS(parse(document), {
    // A default in the document is the hub's to apply, not a promise that a
    // request carries the member, so it must not make a member required.
    defaultNonNullable: false,
    // components["schemas"]["ServerRecord"] is also exported as ServerRecord,
    // KVEntry as KVEntry.
    rootTypes: true,
    rootTypesNoSchemaPrefix: true,
    rootTypesKeepCasing: true,
  });
  const schema = banner + astToString(ast);

  const draft = /\*\*Status:\*\* draft (\d+\.\d+)/.exec(await readFile(protocolURL, "utf8"));
  if (!draft) {
    throw new Error("spec/protocol.md carries no **Status:** draft line");
  }
  const openapiVersion = parse(document)?.info?.version;
  if (typeof openapiVersion !== "string" || openapiVersion === "") {
    throw new Error("spec/openapi-admin.yaml carries no info.version");
  }
  const version =
    banner +
    "/** The draft of spec/protocol.md this package was generated against. */\n" +
    `export const PROTOCOL_DRAFT = ${JSON.stringify(draft[1])};\n\n` +
    "/** The info.version of spec/openapi-admin.yaml this package was generated from. */\n" +
    `export const OPENAPI_VERSION = ${JSON.stringify(openapiVersion)};\n`;

  return [
    [schemaURL, schema],
    [versionURL, version],
  ];
}

const check = process.argv.includes("--check");
let stale = false;
for (const [url, contents] of await render()) {
  const path = fileURLToPath(url);
  if (!check) {
    await writeFile(url, contents);
    console.log(`wrote ${path}`);
    continue;
  }
  let committed = "";
  try {
    committed = (await readFile(url, "utf8")).replaceAll("\r\n", "\n");
  } catch {
    // A missing file is stale like any other.
  }
  if (committed !== contents) {
    console.error(`${path} is stale: run \`npm run generate\` and commit the result`);
    stale = true;
  }
}
if (stale) {
  process.exit(1);
}
if (check) {
  console.log("generated files are up to date");
}
